export enum JobCardState {
	WORKER_APPLIED = 'WORKER_APPLIED',
	ACCEPTED = 'ACCEPTED',
	READY_TO_DEPLOY = 'READY_TO_DEPLOY',
	DEPLOYMENT_COMPLETE = 'DEPLOYMENT_COMPLETE',
	COMPLETED = 'COMPLETED',
	CANCELLED = 'CANCELLED',
}
