export enum WORKER_APPLICATION_STATUS {
	COULD_NOT_CONNECT = 'COULD_NOT_CONNECT',
	INCORRECT = 'INCORRECT',
	REJECTED = 'REJECTED',
	IN_PROGRESS = 'IN_PROGRESS',
	HIRED = 'HIRED',
	WORK_STARTED = 'WORK_STARTED',
}
