name: build and deploy
on:
  push:
    branches:
      - dev
env:
  PROJECT_ID: ${{ secrets.GKE_DEV_PROJECT }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GKE_DEV_SA_KEY }}
  IMAGE: app
  REPOSITORY: ph-dev-web-app
  GKE_ZONE: asia-south1
  GKE_CLUSTER: ph-dev
  GAR_LOCATION: asia-south1
  DEPLOYMENT_NAME: ph-web

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set branch environments
        run: |-
          echo "NEXT_PUBLIC_SERVER_URL=${{secrets.NEXT_PUBLIC_STAGE_SERVER_URL_VAR}}" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure docker with gcloud
        run: |-
          gcloud --quiet auth configure-docker "$GAR_LOCATION-docker.pkg.dev"

      # Get the GKE credentials so we can deploy to the cluster
      - name: Configure GKE Credentials
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ env.SERVICE_ACCOUNT_KEY }}

      # Build the Docker image
      - name: Build docker image
        run: |-
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg NEXT_PUBLIC_SERVER_URL_VAR="$NEXT_PUBLIC_SERVER_URL" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish to GAR
        run: |-
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl --namespace default set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
          kubectl --namespace default rollout status deployment/$DEPLOYMENT_NAME
